//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinCircleDLL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class regFlightCsvModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal regFlightCsvModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinCircleDLL.regFlightCsvModel", typeof(regFlightCsvModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feature1,feature2,corrlation,threashold,circle_x,circle_y,radius
        ///aileron_0,engine_rpm,0,1839.329718,-0.003914,1331.06165,1331.06165
        ///elevator,engine_rpm,0,1872.667975,0.003914,1331.06165,1331.06165
        ///rudder,engine_rpm,0,0,0,1331.06165,1331.06165
        ///flaps,engine_rpm,0,0,0,1331.06165,1331.06165
        ///slats,engine_rpm,0,0,0,1331.06165,1331.06165
        ///speedbrake,engine_rpm,0,0,0,1331.06165,1331.06165
        ///throttle_0,engine_rpm,0.9522346,1053.607535,0.449218005,1331.06165,1331.06177
        ///throttle_1,engine_rpm,0,0,0,1331.06165,1331 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string reg_flight_model {
            get {
                return ResourceManager.GetString("reg_flight_model", resourceCulture);
            }
        }
    }
}
